services:
  web:
    container_name: yournamehere
    build: https://${GITHUB_USERNAME}:${GITHUB_AUTH_TOKEN}@github.com
    ports:
      - 80:80
    user: "1000:1000"
    restart: unless-stopped
    volumes:
      - './logfiles:/app/storage/logs'
    tty: true
    env_file:
      - .env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
